name: ip_geolocation_api_mtec
description: A dart package to flutter or dart projects to get your geolocation data from your IP.
version: 0.0.1
author: Miguel Tec <li.migueltec@gmail.com>
homepage: https://github.com/migueltec/dart-ip-geolocation-api.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
