name: ip_geolocation_api
description: A new Flutter package project.
version: 0.0.1
author: Miguel Tec
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
